[project]
name = "p-shuhua"
version = "1.0.0"
description = "ai-agent for web site lambda19.org"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.2.0",
    "openpyxl>=3.1.0",
    "python-dotenv>=1.0.0",
    "openai-agents[sqlalchemy]>=0.17.5",
    "aiosqlite>=0.22.1",
    "uuid-utils>=0.16.2",
]
